// <auto-generated />
using System;
using DogusCay.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogusCay.DataAccess.Migrations
{
    [DbContext(typeof(DogusCayContext))]
    [Migration("20250626122654_detailiskontoAlanlariEkleme")]
    partial class detailiskontoAlanlariEkleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogusCay.Entity.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Distributor", b =>
                {
                    b.Property<int>("DistributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributorId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("DistributorErcKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KanalId")
                        .HasColumnType("int");

                    b.HasKey("DistributorId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("KanalId");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Kanal", b =>
                {
                    b.Property<int>("KanalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KanalId"));

                    b.Property<string>("KanalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KanalId");

                    b.ToTable("Kanals");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.MalYuklemeTalep.MalYuklemeTalepForm", b =>
                {
                    b.Property<int>("MalYuklemeTalepFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MalYuklemeTalepFormId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BrutTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<int>("KanalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Maliyet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OnaylayanAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("PointGroupTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.Property<int>("TalepDurumu")
                        .HasColumnType("int");

                    b.Property<int>("TalepTip")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToplamAgirlikKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MalYuklemeTalepFormId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("DistributorId");

                    b.HasIndex("KanalId");

                    b.HasIndex("OnaylayanAdminId");

                    b.HasIndex("PointGroupTypeId");

                    b.HasIndex("PointId");

                    b.ToTable("MalYuklemeTalepForms");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.MalYuklemeTalep.MalYuklemeTalepFormDetail", b =>
                {
                    b.Property<int>("MalYuklemeTalepFormDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MalYuklemeTalepFormDetailId"));

                    b.Property<decimal>("ApproximateWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BrutTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Discount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Discount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ErpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FixedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KoliIciAdet")
                        .HasColumnType("int");

                    b.Property<int>("MalYuklemeTalepFormId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Maliyet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetAdetFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("SubSubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.HasKey("MalYuklemeTalepFormDetailId");

                    b.HasIndex("MalYuklemeTalepFormId");

                    b.ToTable("MalYuklemeTalepFormDetails");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Point", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<int?>("KanalId")
                        .HasColumnType("int");

                    b.Property<string>("PointErc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PointGroupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PointId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("DistributorId");

                    b.HasIndex("KanalId");

                    b.HasIndex("PointGroupTypeId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.PointGroupType", b =>
                {
                    b.Property<int>("PointGroupTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointGroupTypeId"));

                    b.Property<string>("PointGroupTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PointGroupTypeId");

                    b.ToTable("PointGroupTypes");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("ApproximateWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ErpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<int>("KoliIciAdet")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<decimal>("IskontoAltiPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SaleTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalNetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("PointId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.SaleType", b =>
                {
                    b.Property<int>("SaleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleTypeId"));

                    b.Property<string>("SaleTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SaleTypeId");

                    b.ToTable("SaleTypes");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.UnitType", b =>
                {
                    b.Property<int>("UnitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitTypeId"));

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitTypeId");

                    b.ToTable("UnitTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TalepForm", b =>
                {
                    b.Property<int>("TalepFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalepFormId"));

                    b.Property<decimal>("AdetFarkDonusuTL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ApproximateWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BrutTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("ErpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Iskonto1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Iskonto2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Iskonto3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Iskonto4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KampanyaDonusAdedi")
                        .HasColumnType("int");

                    b.Property<string>("KampanyaResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KanalId")
                        .HasColumnType("int");

                    b.Property<int?>("KoliIciAdet")
                        .HasColumnType("int");

                    b.Property<int>("KoliIciToplamAdet")
                        .HasColumnType("int");

                    b.Property<decimal>("KoliToplamAgirligiKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ListeFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Maliyet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OnaylayanAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("PointGroupTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("SabitBedelTL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SonAdetFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("SubSubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TalepDurumu")
                        .HasColumnType("int");

                    b.Property<int>("TalepTip")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("TalepFormId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DistributorId");

                    b.HasIndex("KanalId");

                    b.HasIndex("OnaylayanAdminId");

                    b.HasIndex("PointGroupTypeId");

                    b.HasIndex("PointId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("SubSubCategoryId");

                    b.ToTable("TalepForms");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Category", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Distributor", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Kanal", "Kanal")
                        .WithMany("Distributors")
                        .HasForeignKey("KanalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Kanal");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.MalYuklemeTalep.MalYuklemeTalepForm", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DogusCay.Entity.Entities.Kanal", "Kanal")
                        .WithMany()
                        .HasForeignKey("KanalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.AppUser", "OnaylayanAdmin")
                        .WithMany()
                        .HasForeignKey("OnaylayanAdminId");

                    b.HasOne("DogusCay.Entity.Entities.PointGroupType", "PointGroupType")
                        .WithMany()
                        .HasForeignKey("PointGroupTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DogusCay.Entity.Entities.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Distributor");

                    b.Navigation("Kanal");

                    b.Navigation("OnaylayanAdmin");

                    b.Navigation("Point");

                    b.Navigation("PointGroupType");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.MalYuklemeTalep.MalYuklemeTalepFormDetail", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.MalYuklemeTalep.MalYuklemeTalepForm", "MalYuklemeTalepForm")
                        .WithMany("MalYuklemeTalepFormDetails")
                        .HasForeignKey("MalYuklemeTalepFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MalYuklemeTalepForm");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Point", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppUser", "AppUser")
                        .WithMany("Points")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Distributor", "Distributor")
                        .WithMany("Points")
                        .HasForeignKey("DistributorId");

                    b.HasOne("DogusCay.Entity.Entities.Kanal", "Kanal")
                        .WithMany("Points")
                        .HasForeignKey("KanalId");

                    b.HasOne("DogusCay.Entity.Entities.PointGroupType", "PointGroupType")
                        .WithMany("Points")
                        .HasForeignKey("PointGroupTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");

                    b.Navigation("Distributor");

                    b.Navigation("Kanal");

                    b.Navigation("PointGroupType");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Product", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.UnitType", "UnitType")
                        .WithMany("Products")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Sale", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.PaymentType", "PaymentType")
                        .WithMany("Sales")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Point", "Point")
                        .WithMany("Sales")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.SaleType", null)
                        .WithMany("Sales")
                        .HasForeignKey("SaleTypeId");

                    b.HasOne("DogusCay.Entity.Entities.AppUser", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("Point");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TalepForm", b =>
                {
                    b.HasOne("DogusCay.Entity.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DogusCay.Entity.Entities.Kanal", "Kanal")
                        .WithMany()
                        .HasForeignKey("KanalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.AppUser", "OnaylayanAdmin")
                        .WithMany()
                        .HasForeignKey("OnaylayanAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DogusCay.Entity.Entities.PointGroupType", "PointGroupType")
                        .WithMany()
                        .HasForeignKey("PointGroupTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DogusCay.Entity.Entities.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusCay.Entity.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("DogusCay.Entity.Entities.Category", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId");

                    b.HasOne("DogusCay.Entity.Entities.Category", "SubSubCategory")
                        .WithMany()
                        .HasForeignKey("SubSubCategoryId");

                    b.Navigation("AppUser");

                    b.Navigation("Category");

                    b.Navigation("Distributor");

                    b.Navigation("Kanal");

                    b.Navigation("OnaylayanAdmin");

                    b.Navigation("Point");

                    b.Navigation("PointGroupType");

                    b.Navigation("Product");

                    b.Navigation("SubCategory");

                    b.Navigation("SubSubCategory");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.AppUser", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Distributor", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Kanal", b =>
                {
                    b.Navigation("Distributors");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.MalYuklemeTalep.MalYuklemeTalepForm", b =>
                {
                    b.Navigation("MalYuklemeTalepFormDetails");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.PaymentType", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Point", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.PointGroupType", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.SaleType", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DogusCay.Entity.Entities.UnitType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
